spring.application.name=backend
jwt.secret=${JWT_SECRET:TeacherAI-Secure-Secret-Key-For-JWT-256Bits!!}
server.port=${PORT:8080}

# SpringEdge SMS
springedge.api.key=${SPRINGEDGE_API_KEY}
springedge.sender.id=${SPRINGEDGE_SENDER_ID}
