import { useState } from "react";
import DashboardLayout from "../layout/DashboardLayout";
import api from "../services/api";

import jsPDF from "jspdf";
import html2canvas from "html2canvas";
import { saveAs } from "file-saver";
import { Document, Packer, Paragraph, TextRun, Header, Footer } from "docx";

export default function AssessmentGenerator() {
  const [subject, setSubject]     = useState("");
  const [grade, setGrade]         = useState("");
  const [topic, setTopic]         = useState("");
  const [difficulty, setDifficulty] = useState("Medium");
  const [language, setLanguage]   = useState("English");
  const [syllabus, setSyllabus]   = useState("");
  const [examType, setExamType]   = useState("");

  const [sections, setSections]   = useState([]);

  const [loading, setLoading]           = useState(false);
  const [paper, setPaper]               = useState("");
  const [answerKey, setAnswerKey]       = useState("");
  const [loadingAnswer, setLoadingAnswer] = useState(false);
  const [error, setError]               = useState("");

  const SECTION_LABELS = ["A", "B", "C", "D", "E"];

  /* ── Section handling ── */
  const addSection = (label) => {
    if (sections.some((s) => s.sectionLabel === label)) return;
    setSections([...sections, { sectionLabel: label, questionType: "MCQ", questionCount: 1, marksPerQuestion: 1 }]);
  };

  const updateSection = (index, field, value) => {
    const updated = [...sections];
    updated[index][field] = field.includes("Count") || field.includes("marks") ? Number(value) : value;
    setSections(updated);
  };

  const removeSection = (index) => setSections(sections.filter((_, i) => i !== index));

  /* ── Generate paper ── */
  const handleGenerate = async (e) => {
    e.preventDefault();
    setLoading(true);
    setError("");
    setPaper("");
    setAnswerKey("");
    if (sections.length === 0) { setError("Please add at least one section."); setLoading(false); return; }
    try {
      const res = await api.post("/api/assessment/generate", { syllabus, examType, subject, grade, topic, difficulty, language, sections });
      setPaper(res.data);
    } catch (err) {
      console.error(err);
      setError("Failed to generate assessment. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  /* ── Answer key ── */
  const generateAnswerKey = async () => {
    if (!paper) return;
    setLoadingAnswer(true);
    setAnswerKey("");
    try {
      const res = await api.post("/api/assessment/answer-key", { questionPaper: paper, language });
      setAnswerKey(res.data);
    } catch (err) {
      console.error(err);
      alert("Failed to generate answer key");
    } finally {
      setLoadingAnswer(false);
    }
  };

  /* ── PDF download ── */
  const downloadPDF = async (elementId, fileName) => {
    const element = document.getElementById(elementId);
    if (!element) return;
    const canvas = await html2canvas(element, { scale: 2 });
    const imgData = canvas.toDataURL("image/png");
    const pdf = new jsPDF("p", "mm", "a4");
    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    const headerHeight = 30, footerHeight = 20, margin = 10;
    const usableWidth = pageWidth - margin * 2;
    const usableHeight = pageHeight - headerHeight - footerHeight;
    const imgHeight = (canvas.height * usableWidth) / canvas.width;
    let heightLeft = imgHeight, positionY = headerHeight, page = 1;
    const today = new Date().toLocaleDateString();
    const drawHF = () => {
      pdf.setFontSize(12);
      pdf.text("Assessment Question Paper", pageWidth / 2, 15, { align: "center" });
      pdf.setFontSize(10);
      pdf.text(`Subject: ${subject} | Class: ${grade} | Date: ${today}`, pageWidth / 2, 22, { align: "center" });
      pdf.setFontSize(9);
      pdf.text(`Generated by Teacher AI | Page ${page}`, pageWidth / 2, pageHeight - 8, { align: "center" });
    };
    drawHF();
    pdf.addImage(imgData, "PNG", margin, positionY, usableWidth, imgHeight);
    heightLeft -= usableHeight;
    while (heightLeft > 0) {
      page++;
      pdf.addPage();
      drawHF();
      positionY = headerHeight - (imgHeight - heightLeft);
      pdf.addImage(imgData, "PNG", margin, positionY, usableWidth, imgHeight);
      heightLeft -= usableHeight;
    }
    pdf.save(fileName);
  };

  /* ── Word download ── */
  const downloadWord = async (content, fileName) => {
    const today = new Date().toLocaleDateString();
    const doc = new Document({
      sections: [{
        headers: { default: new Header({ children: [
          new Paragraph({ children: [new TextRun({ text: "Assessment Question Paper", bold: true, size: 28 })], alignment: "center" }),
          new Paragraph({ children: [new TextRun({ text: `Subject: ${subject} | Class: ${grade} | Date: ${today}`, size: 22 })], alignment: "center" })
        ]})},
        footers: { default: new Footer({ children: [new Paragraph({ children: [new TextRun("Generated by Teacher AI")], alignment: "center" })] }) },
        children: content.split("\n").map((line) => new Paragraph({ children: [new TextRun({ text: line, size: 22 })] }))
      }]
    });
    const blob = await Packer.toBlob(doc);
    saveAs(blob, fileName);
  };

  return (
    <DashboardLayout>
      <div className="page-header">
        <h1 className="page-title">Assessment Generator</h1>
        <p className="page-subtitle">Configure your question paper and generate it with AI.</p>
      </div>

      <div className="card" style={{ maxWidth: 760 }}>
        <form onSubmit={handleGenerate}>

          {/* Basic info */}
          <div className="form-grid">
            <div className="form-field">
              <label className="form-label">Board</label>
              <select className="form-select" value={syllabus} onChange={(e) => setSyllabus(e.target.value)} required>
                <option value="">Select board</option>
                <option>CBSE</option>
                <option>ICSE</option>
                <option>Bihar Board</option>
              </select>
            </div>

            <div className="form-field">
              <label className="form-label">Exam Type</label>
              <select className="form-select" value={examType} onChange={(e) => setExamType(e.target.value)} required>
                <option value="">Select exam type</option>
                <option>Unit Test</option>
                <option>Monthly Test</option>
                <option>Mid-Term</option>
                <option>Final</option>
              </select>
            </div>

            <div className="form-field">
              <label className="form-label">Subject</label>
              <input className="form-input" placeholder="e.g. Mathematics" value={subject} onChange={(e) => setSubject(e.target.value)} required />
            </div>

            <div className="form-field">
              <label className="form-label">Class</label>
              <input className="form-input" placeholder="e.g. 10" value={grade} onChange={(e) => setGrade(e.target.value)} required />
            </div>

            <div className="form-field form-field-full">
              <label className="form-label">Topic</label>
              <input className="form-input" placeholder="e.g. Quadratic Equations" value={topic} onChange={(e) => setTopic(e.target.value)} required />
            </div>

            <div className="form-field">
              <label className="form-label">Difficulty</label>
              <select className="form-select" value={difficulty} onChange={(e) => setDifficulty(e.target.value)}>
                <option>Easy</option>
                <option>Medium</option>
                <option>Hard</option>
              </select>
            </div>

            <div className="form-field">
              <label className="form-label">Language</label>
              <select className="form-select" value={language} onChange={(e) => setLanguage(e.target.value)}>
                <option>English</option>
                <option>Hindi</option>
              </select>
            </div>
          </div>

          {/* Sections */}
          <p className="section-divider-label" style={{ marginTop: 24 }}>Sections</p>

          <div className="section-labels">
            {SECTION_LABELS.map((l) => (
              <button
                key={l}
                type="button"
                className="section-add-btn"
                onClick={() => addSection(l)}
                disabled={sections.some((s) => s.sectionLabel === l)}
              >
                + Section {l}
              </button>
            ))}
          </div>

          {sections.length > 0 && (
            <div style={{ marginBottom: 8 }}>
              <div style={{ display: "grid", gridTemplateColumns: "40px 1fr 80px 80px auto", gap: 8, padding: "0 12px", marginBottom: 6 }}>
                <span style={{ fontSize: 11, color: "#94a3b8", fontWeight: 600 }}></span>
                <span style={{ fontSize: 11, color: "#94a3b8", fontWeight: 600 }}>TYPE</span>
                <span style={{ fontSize: 11, color: "#94a3b8", fontWeight: 600 }}>QTY</span>
                <span style={{ fontSize: 11, color: "#94a3b8", fontWeight: 600 }}>MARKS</span>
                <span></span>
              </div>
              {sections.map((s, i) => (
                <div key={i} className="section-row">
                  <div className="section-badge">{s.sectionLabel}</div>
                  <select className="form-select" value={s.questionType} onChange={(e) => updateSection(i, "questionType", e.target.value)} style={{ padding: "7px 10px" }}>
                    <option>MCQ</option>
                    <option>SHORT</option>
                    <option>LONG</option>
                    <option>ASSERTION</option>
                    <option>PUZZLE</option>
                  </select>
                  <input type="number" className="form-input" min="1" value={s.questionCount} onChange={(e) => updateSection(i, "questionCount", e.target.value)} style={{ padding: "7px 10px", textAlign: "center" }} />
                  <input type="number" className="form-input" min="1" value={s.marksPerQuestion} onChange={(e) => updateSection(i, "marksPerQuestion", e.target.value)} style={{ padding: "7px 10px", textAlign: "center" }} />
                  <button type="button" className="section-remove" onClick={() => removeSection(i)}>✕</button>
                </div>
              ))}
            </div>
          )}

          {error && (
            <div className="alert-error">
              <span>⚠️</span> {error}
            </div>
          )}

          <div style={{ marginTop: 20 }}>
            <button type="submit" className="btn-primary" disabled={loading}>
              {loading && <span className="spinner" />}
              {loading ? "Generating…" : "✨ Generate Assessment"}
            </button>
          </div>
        </form>
      </div>

      {/* Question paper result */}
      {paper && (
        <div className="result-box">
          <div className="result-box-header">
            <span className="result-box-title">📄 Question Paper</span>
            <div className="result-box-actions">
              <button className="btn-secondary" onClick={() => downloadPDF("paper-content", "Question_Paper.pdf")}>⬇ PDF</button>
              <button className="btn-secondary" onClick={() => downloadWord(paper, "Question_Paper.docx")}>⬇ Word</button>
              <button className="btn-primary" onClick={generateAnswerKey} disabled={loadingAnswer}>
                {loadingAnswer && <span className="spinner" />}
                {loadingAnswer ? "Generating…" : "🔑 Answer Key"}
              </button>
            </div>
          </div>
          <pre id="paper-content" className="result-text">{paper}</pre>
        </div>
      )}

      {/* Answer key result */}
      {answerKey && (
        <div className="result-box">
          <div className="result-box-header">
            <span className="result-box-title">🔑 Answer Key</span>
            <div className="result-box-actions">
              <button className="btn-secondary" onClick={() => downloadPDF("answer-content", "Answer_Key.pdf")}>⬇ PDF</button>
              <button className="btn-secondary" onClick={() => downloadWord(answerKey, "Answer_Key.docx")}>⬇ Word</button>
            </div>
          </div>
          <pre id="answer-content" className="result-text">{answerKey}</pre>
        </div>
      )}
    </DashboardLayout>
  );
}
