import { useState, useEffect } from "react";
import DashboardLayout from "../layout/DashboardLayout";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import SchoolLogoUpload from "../components/SchoolLogoUpload";

const GRADES = ["LKG","UKG","Class 1","Class 2","Class 3","Class 4","Class 5",
                "Class 6","Class 7","Class 8","Class 9","Class 10","Class 11","Class 12"];
const BOARDS = ["CBSE","ICSE","Bihar Board"];
const EXAM_TYPES = ["Unit Test 1","Unit Test 2","Unit Test 3","Half Yearly",
                    "Pre-Board","Annual / Final","Practical","Internal Assessment"];
const DURATIONS = ["30 min","1 hr","1.5 hrs","2 hrs","2.5 hrs","3 hrs","3.5 hrs"];

const STORAGE_KEY = "exam_schedule_v1";
const load = () => { try { return JSON.parse(localStorage.getItem(STORAGE_KEY) || "[]"); } catch { return []; } };
const save = (d) => localStorage.setItem(STORAGE_KEY, JSON.stringify(d));
const todayStr = () => new Date().toISOString().slice(0, 10);
const fmt = (d) => new Date(d + "T00:00:00").toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" });
const dayOf = (d) => new Date(d + "T00:00:00").toLocaleDateString("en-IN", { weekday: "long" });

const TYPE_COLORS = {
  "Unit Test 1":          ["#eff6ff","#2563eb"],
  "Unit Test 2":          ["#eff6ff","#2563eb"],
  "Unit Test 3":          ["#eff6ff","#2563eb"],
  "Half Yearly":          ["#fef3c7","#d97706"],
  "Pre-Board":            ["#fdf4ff","#9333ea"],
  "Annual / Final":       ["#fef2f2","#dc2626"],
  "Practical":            ["#f0fdf4","#16a34a"],
  "Internal Assessment":  ["#f0f9ff","#0369a1"],
};

export default function ExamSchedule() {
  const [exams, setExams] = useState(load);
  const [grade, setGrade] = useState("Class 6");
  const [board, setBoard] = useState("CBSE");
  const [logo, setLogo] = useState(() => localStorage.getItem("school_logo") || null);
  const [showForm, setShowForm] = useState(false);

  const [fSubject, setFSubject] = useState("");
  const [fType, setFType] = useState(EXAM_TYPES[0]);
  const [fDate, setFDate] = useState(todayStr());
  const [fTime, setFTime] = useState("09:00");
  const [fDuration, setFDuration] = useState("3 hrs");
  const [fRoom, setFRoom] = useState("");

  useEffect(() => { save(exams); }, [exams]);

  const filtered = exams
    .filter(e => e.grade === grade && e.board === board)
    .sort((a, b) => a.date.localeCompare(b.date));
  const now = todayStr();
  const upcoming = filtered.filter(e => e.date >= now);
  const past     = filtered.filter(e => e.date < now);

  const addExam = (e) => {
    e.preventDefault();
    if (!fSubject.trim()) return;
    setExams(prev => [...prev, {
      id: Date.now(), grade, board,
      subject: fSubject.trim(), examType: fType,
      date: fDate, startTime: fTime, duration: fDuration, room: fRoom.trim(),
    }]);
    setFSubject(""); setFRoom(""); setShowForm(false);
  };

  const removeExam = (id) => setExams(prev => prev.filter(e => e.id !== id));

  const downloadPDF = () => {
    const doc = new jsPDF({ orientation: "portrait", format: "a4", unit: "mm" });
    const pw = doc.internal.pageSize.getWidth();
    if (logo) { try { doc.addImage(logo, "PNG", 10, 8, 18, 18); } catch {} }
    doc.setFont("helvetica", "bold"); doc.setFontSize(15);
    doc.text("Exam Timetable", pw / 2, 16, { align: "center" });
    doc.setFont("helvetica", "normal"); doc.setFontSize(10);
    doc.text(`${grade} — ${board}`, pw / 2, 23, { align: "center" });
    doc.text(new Date().toLocaleDateString("en-IN"), pw / 2, 28, { align: "center" });

    autoTable(doc, {
      head: [["Date", "Day", "Exam Type", "Subject", "Time", "Duration", "Venue"]],
      body: upcoming.map(ex => [
        fmt(ex.date), dayOf(ex.date), ex.examType, ex.subject,
        ex.startTime, ex.duration, ex.room || "—",
      ]),
      startY: 35,
      styles: { fontSize: 9, cellPadding: 3 },
      headStyles: { fillColor: [30, 58, 138], textColor: 255, fontStyle: "bold" },
      columnStyles: {
        0: { cellWidth: 24 }, 1: { cellWidth: 20 }, 2: { cellWidth: 30 },
        3: { cellWidth: 40 }, 4: { cellWidth: 16 }, 5: { cellWidth: 18 }, 6: { cellWidth: 22 },
      },
      margin: { left: 14, right: 14 },
    });

    doc.setFontSize(8); doc.setTextColor(148, 163, 184);
    doc.text("Generated by SmartBoard AI", pw / 2, doc.internal.pageSize.getHeight() - 8, { align: "center" });
    doc.save(`ExamSchedule_${grade.replace(/\s/g,"")}_${board}.pdf`);
  };

  return (
    <DashboardLayout>
      <div className="page-header">
        <h1 className="page-title">Exam Schedule Manager</h1>
        <p className="page-subtitle">Plan unit tests, half-yearly and final exams — download printable timetables for students.</p>
      </div>

      <div className="card" style={{ maxWidth: 820, marginBottom: 20 }}>
        <div style={{ display: "flex", gap: 12, flexWrap: "wrap", alignItems: "flex-end" }}>
          <div className="form-field" style={{ minWidth: 140 }}>
            <label className="form-label">Class</label>
            <select className="form-select" value={grade} onChange={e => setGrade(e.target.value)}>
              {GRADES.map(g => <option key={g}>{g}</option>)}
            </select>
          </div>
          <div className="form-field" style={{ minWidth: 140 }}>
            <label className="form-label">Board</label>
            <select className="form-select" value={board} onChange={e => setBoard(e.target.value)}>
              {BOARDS.map(b => <option key={b}>{b}</option>)}
            </select>
          </div>
          <div style={{ marginLeft: "auto", display: "flex", gap: 10, alignItems: "flex-end" }}>
            <SchoolLogoUpload logo={logo} setLogo={setLogo} />
            {upcoming.length > 0 && (
              <button className="btn-secondary" onClick={downloadPDF}>⬇ PDF Timetable</button>
            )}
            <button className="btn-primary" onClick={() => setShowForm(v => !v)}>
              {showForm ? "✕ Cancel" : "+ Add Exam"}
            </button>
          </div>
        </div>
      </div>

      {showForm && (
        <div className="card" style={{ maxWidth: 820, marginBottom: 20 }}>
          <p style={{ fontWeight: 700, color: "#0f172a", marginBottom: 16 }}>Add Exam — {grade} ({board})</p>
          <form onSubmit={addExam}>
            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 }}>
              <div className="form-field">
                <label className="form-label">Subject *</label>
                <input className="form-input" placeholder="e.g. Mathematics" value={fSubject}
                  onChange={e => setFSubject(e.target.value)} required />
              </div>
              <div className="form-field">
                <label className="form-label">Exam Type</label>
                <select className="form-select" value={fType} onChange={e => setFType(e.target.value)}>
                  {EXAM_TYPES.map(t => <option key={t}>{t}</option>)}
                </select>
              </div>
              <div className="form-field">
                <label className="form-label">Date *</label>
                <input type="date" className="form-input" value={fDate}
                  onChange={e => setFDate(e.target.value)} required />
              </div>
              <div className="form-field">
                <label className="form-label">Start Time</label>
                <input type="time" className="form-input" value={fTime}
                  onChange={e => setFTime(e.target.value)} />
              </div>
              <div className="form-field">
                <label className="form-label">Duration</label>
                <select className="form-select" value={fDuration} onChange={e => setFDuration(e.target.value)}>
                  {DURATIONS.map(d => <option key={d}>{d}</option>)}
                </select>
              </div>
              <div className="form-field">
                <label className="form-label">Venue / Room <span style={{ fontWeight: 400, color: "#94a3b8" }}>(optional)</span></label>
                <input className="form-input" placeholder="e.g. Hall A, Room 12" value={fRoom}
                  onChange={e => setFRoom(e.target.value)} />
              </div>
            </div>
            <div style={{ marginTop: 16, display: "flex", justifyContent: "flex-end", gap: 10 }}>
              <button type="button" className="btn-secondary" onClick={() => setShowForm(false)}>Cancel</button>
              <button type="submit" className="btn-primary">Add to Schedule</button>
            </div>
          </form>
        </div>
      )}

      {filtered.length === 0 ? (
        <div className="card" style={{ maxWidth: 820, textAlign: "center", padding: "48px 0", color: "#94a3b8" }}>
          <div style={{ fontSize: 40, marginBottom: 8 }}>📅</div>
          <p>No exams scheduled for {grade}. Click "+ Add Exam" to get started.</p>
        </div>
      ) : (
        <div style={{ maxWidth: 820 }}>
          {upcoming.length > 0 && (
            <>
              <p style={{ fontWeight: 700, color: "#0f172a", fontSize: 12, marginBottom: 10,
                textTransform: "uppercase", letterSpacing: 1 }}>Upcoming ({upcoming.length})</p>
              <div style={{ display: "flex", flexDirection: "column", gap: 10, marginBottom: 24 }}>
                {upcoming.map(ex => <ExamCard key={ex.id} ex={ex} onRemove={removeExam} isPast={false} />)}
              </div>
            </>
          )}
          {past.length > 0 && (
            <>
              <p style={{ fontWeight: 700, color: "#94a3b8", fontSize: 12, marginBottom: 10,
                textTransform: "uppercase", letterSpacing: 1 }}>Past ({past.length})</p>
              <div style={{ display: "flex", flexDirection: "column", gap: 8, opacity: 0.55 }}>
                {[...past].reverse().map(ex => <ExamCard key={ex.id} ex={ex} onRemove={removeExam} isPast />)}
              </div>
            </>
          )}
        </div>
      )}
    </DashboardLayout>
  );
}

function ExamCard({ ex, onRemove }) {
  const [bg, tc] = TYPE_COLORS[ex.examType] || ["#f8fafc","#64748b"];
  const d = new Date(ex.date + "T00:00:00");
  return (
    <div style={{
      display: "flex", alignItems: "center", gap: 16, padding: "14px 18px",
      borderRadius: 12, background: "#fff", border: "1px solid #e2e8f0",
      boxShadow: "0 1px 4px rgba(0,0,0,0.05)",
    }}>
      <div style={{ textAlign: "center", minWidth: 52 }}>
        <div style={{ fontSize: 22, fontWeight: 900, color: "#0f172a", lineHeight: 1 }}>{d.getDate()}</div>
        <div style={{ fontSize: 11, color: "#64748b", fontWeight: 600 }}>
          {d.toLocaleDateString("en-IN", { month: "short" })}
        </div>
        <div style={{ fontSize: 10, color: "#94a3b8" }}>
          {d.toLocaleDateString("en-IN", { weekday: "short" })}
        </div>
      </div>
      <div style={{ flex: 1 }}>
        <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 4, flexWrap: "wrap" }}>
          <span style={{ fontSize: 15, fontWeight: 700, color: "#0f172a" }}>{ex.subject}</span>
          <span style={{ background: bg, color: tc, borderRadius: 6, padding: "2px 10px", fontSize: 11, fontWeight: 700 }}>
            {ex.examType}
          </span>
        </div>
        <div style={{ fontSize: 12, color: "#64748b", display: "flex", gap: 14 }}>
          <span>🕐 {ex.startTime}</span>
          <span>⏱ {ex.duration}</span>
          {ex.room && <span>📍 {ex.room}</span>}
        </div>
      </div>
      <button onClick={() => onRemove(ex.id)}
        style={{ background: "none", border: "none", color: "#94a3b8", cursor: "pointer", fontSize: 18, padding: 4 }}>
        ✕
      </button>
    </div>
  );
}
