export default function TermsOfService() {
  return (
    <div style={{ maxWidth: 760, margin: "0 auto", padding: "48px 24px", fontFamily: "sans-serif", color: "#1e293b", lineHeight: 1.7 }}>
      <h1 style={{ fontSize: 28, fontWeight: 700, marginBottom: 4 }}>Terms of Service</h1>
      <p style={{ color: "#64748b", marginBottom: 32 }}>Last updated: April 18, 2026</p>

      <section style={{ marginBottom: 28 }}>
        <h2 style={{ fontSize: 18, fontWeight: 600 }}>1. Acceptance of Terms</h2>
        <p>By creating an account or using TeacherAI, you agree to these Terms of Service. If you do not agree, please do not use the service.</p>
      </section>

      <section style={{ marginBottom: 28 }}>
        <h2 style={{ fontSize: 18, fontWeight: 600 }}>2. Description of Service</h2>
        <p>TeacherAI provides AI-powered tools for teachers including lesson plan generation, assessment creation, attendance management, report card remarks, notice generation, monthly planners, and timetable builders.</p>
      </section>

      <section style={{ marginBottom: 28 }}>
        <h2 style={{ fontSize: 18, fontWeight: 600 }}>3. Eligibility</h2>
        <p>You must be at least 18 years old and a qualified or practicing educator to use TeacherAI. By signing up, you confirm you meet these requirements.</p>
      </section>

      <section style={{ marginBottom: 28 }}>
        <h2 style={{ fontSize: 18, fontWeight: 600 }}>4. Account Responsibility</h2>
        <p>You are responsible for keeping your account credentials secure. You agree not to share your account with others. Notify us immediately if you suspect unauthorised access.</p>
      </section>

      <section style={{ marginBottom: 28 }}>
        <h2 style={{ fontSize: 18, fontWeight: 600 }}>5. Acceptable Use</h2>
        <p>You agree not to:</p>
        <ul style={{ paddingLeft: 20 }}>
          <li>Use the service for any unlawful purpose.</li>
          <li>Attempt to reverse-engineer, scrape, or abuse the AI systems.</li>
          <li>Generate content that is harmful, misleading, or violates any applicable law.</li>
          <li>Share, resell, or redistribute AI-generated outputs as your own commercial product without attribution.</li>
        </ul>
      </section>

      <section style={{ marginBottom: 28 }}>
        <h2 style={{ fontSize: 18, fontWeight: 600 }}>6. Plans &amp; Payments</h2>
        <p>TeacherAI offers a FREE plan and a PRO plan (₹199/month). Payments are processed securely. Subscriptions are billed monthly and can be cancelled at any time. No refunds are issued for partial months unless required by law.</p>
      </section>

      <section style={{ marginBottom: 28 }}>
        <h2 style={{ fontSize: 18, fontWeight: 600 }}>7. AI-Generated Content</h2>
        <p>Content generated by TeacherAI is AI-assisted and should be reviewed by you before use. We do not guarantee accuracy, completeness, or curriculum compliance of generated content. You are responsible for the final content you use in your classroom.</p>
      </section>

      <section style={{ marginBottom: 28 }}>
        <h2 style={{ fontSize: 18, fontWeight: 600 }}>8. Intellectual Property</h2>
        <p>TeacherAI and its underlying technology are owned by us. AI-generated outputs created through your inputs are yours to use for educational purposes. You retain ownership of any original content you upload or create.</p>
      </section>

      <section style={{ marginBottom: 28 }}>
        <h2 style={{ fontSize: 18, fontWeight: 600 }}>9. Limitation of Liability</h2>
        <p>To the maximum extent permitted by law, TeacherAI is not liable for any indirect, incidental, or consequential damages arising from use of the service. The service is provided "as is" without warranty of any kind.</p>
      </section>

      <section style={{ marginBottom: 28 }}>
        <h2 style={{ fontSize: 18, fontWeight: 600 }}>10. Termination</h2>
        <p>We may suspend or terminate your account if you violate these terms. You may delete your account at any time by contacting us.</p>
      </section>

      <section style={{ marginBottom: 28 }}>
        <h2 style={{ fontSize: 18, fontWeight: 600 }}>11. Changes to Terms</h2>
        <p>We may update these terms from time to time. Continued use of the service after changes constitutes acceptance of the new terms.</p>
      </section>

      <section style={{ marginBottom: 28 }}>
        <h2 style={{ fontSize: 18, fontWeight: 600 }}>12. Governing Law</h2>
        <p>These terms are governed by the laws of India. Any disputes shall be subject to the jurisdiction of courts in India.</p>
      </section>

      <section style={{ marginBottom: 28 }}>
        <h2 style={{ fontSize: 18, fontWeight: 600 }}>13. Contact</h2>
        <p>For any questions about these terms, contact us at <a href="mailto:avnishweb91@gmail.com" style={{ color: "#2563eb" }}>avnishweb91@gmail.com</a>.</p>
      </section>
    </div>
  );
}
