import { Link } from "react-router-dom";
import { Helmet } from "react-helmet-async";

const SECTIONS = [
  {
    num: "1", color: "#7c3aed", bg: "#f5f3ff", border: "#ddd6fe",
    title: "Acceptance of Terms",
    content: (
      <p>By creating an account or using SmartBoard AI, you agree to these Terms of Service. If you do not agree, please do not use the service.</p>
    ),
  },
  {
    num: "2", color: "#2563eb", bg: "#eff6ff", border: "#bfdbfe",
    title: "Description of Service",
    content: (
      <p>SmartBoard AI provides AI-powered tools for teachers including lesson plan generation, assessment creation, attendance management, report card remarks, notice generation, monthly planners, and timetable builders.</p>
    ),
  },
  {
    num: "3", color: "#059669", bg: "#f0fdf4", border: "#bbf7d0",
    title: "Eligibility",
    content: (
      <p>You must be at least 18 years old and a qualified or practicing educator to use SmartBoard AI. By signing up, you confirm you meet these requirements.</p>
    ),
  },
  {
    num: "4", color: "#d97706", bg: "#fffbeb", border: "#fde68a",
    title: "Account Responsibility",
    content: (
      <p>You are responsible for keeping your account credentials secure. You agree not to share your account with others. Notify us immediately if you suspect unauthorised access.</p>
    ),
  },
  {
    num: "5", color: "#dc2626", bg: "#fef2f2", border: "#fecaca",
    title: "Acceptable Use",
    content: (
      <>
        <p style={{ margin: "0 0 8px" }}>You agree not to:</p>
        <ul style={{ paddingLeft: 20, margin: 0 }}>
          <li>Use the service for any unlawful purpose.</li>
          <li>Attempt to reverse-engineer, scrape, or abuse the AI systems.</li>
          <li>Generate content that is harmful, misleading, or violates any applicable law.</li>
          <li>Share, resell, or redistribute AI-generated outputs as your own commercial product without attribution.</li>
        </ul>
      </>
    ),
  },
  {
    num: "6", color: "#0891b2", bg: "#ecfeff", border: "#a5f3fc",
    title: "Plans & Payments",
    content: (
      <p>SmartBoard AI offers a FREE plan and a PRO plan (₹199/month). Payments are processed securely. Subscriptions are billed monthly and can be cancelled at any time. No refunds are issued for partial months unless required by law.</p>
    ),
  },
  {
    num: "7", color: "#4f46e5", bg: "#eef2ff", border: "#c7d2fe",
    title: "AI-Generated Content",
    content: (
      <p>Content generated by SmartBoard AI is AI-assisted and should be reviewed by you before use. We do not guarantee accuracy, completeness, or curriculum compliance of generated content. You are responsible for the final content you use in your classroom.</p>
    ),
  },
  {
    num: "8", color: "#be185d", bg: "#fdf2f8", border: "#fbcfe8",
    title: "Intellectual Property",
    content: (
      <p>SmartBoard AI and its underlying technology are owned by us. AI-generated outputs created through your inputs are yours to use for educational purposes. You retain ownership of any original content you upload or create.</p>
    ),
  },
  {
    num: "9", color: "#0f766e", bg: "#f0fdfa", border: "#99f6e4",
    title: "Limitation of Liability",
    content: (
      <p>To the maximum extent permitted by law, SmartBoard AI is not liable for any indirect, incidental, or consequential damages arising from use of the service. The service is provided "as is" without warranty of any kind.</p>
    ),
  },
  {
    num: "10", color: "#b45309", bg: "#fff7ed", border: "#fed7aa",
    title: "Termination",
    content: (
      <p>We may suspend or terminate your account if you violate these terms. You may delete your account at any time by contacting us.</p>
    ),
  },
  {
    num: "11", color: "#1d4ed8", bg: "#eff6ff", border: "#bfdbfe",
    title: "Changes to Terms",
    content: (
      <p>We may update these terms from time to time. Continued use of the service after changes constitutes acceptance of the new terms.</p>
    ),
  },
  {
    num: "12", color: "#6d28d9", bg: "#f5f3ff", border: "#ddd6fe",
    title: "Governing Law",
    content: (
      <p>These terms are governed by the laws of India. Any disputes shall be subject to the jurisdiction of courts in India.</p>
    ),
  },
  {
    num: "13", color: "#0e7490", bg: "#ecfeff", border: "#a5f3fc",
    title: "Contact",
    content: (
      <p>For any questions about these terms, contact us at{" "}
        <a href="mailto:support@smartboard.co.in" style={{ color: "#2563eb" }}>support@smartboard.co.in</a>.
      </p>
    ),
  },
];

export default function TermsOfService() {
  return (
    <div style={{ minHeight: "100vh", background: "linear-gradient(160deg, #f5f3ff 0%, #eff6ff 50%, #fdf2f8 100%)", fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif" }}>
      <Helmet>
        <title>Terms &amp; Conditions — SmartBoard AI</title>
        <meta name="description" content="Terms and conditions for using SmartBoard AI — the AI-powered teaching assistant for Indian schools. Read our usage policies, subscription terms and refund policy." />
        <link rel="canonical" href="https://www.smartboard.co.in/terms" />
      </Helmet>

      {/* Hero header */}
      <div style={{ background: "linear-gradient(135deg, #4c1d95 0%, #6d28d9 50%, #be185d 100%)", padding: "52px 24px 44px", textAlign: "center", color: "#fff", position: "relative", overflow: "hidden" }}>
        <div style={{ position: "absolute", top: -60, right: -60, width: 200, height: 200, borderRadius: "50%", background: "rgba(255,255,255,0.06)" }} />
        <div style={{ position: "absolute", bottom: -80, left: -40, width: 240, height: 240, borderRadius: "50%", background: "rgba(255,255,255,0.05)" }} />
        <div style={{ fontSize: 52, marginBottom: 14, position: "relative" }}>📜</div>
        <h1 style={{ fontSize: 34, fontWeight: 800, margin: "0 0 10px", letterSpacing: "-0.5px", position: "relative" }}>Terms &amp; Conditions</h1>
        <p style={{ fontSize: 14, color: "rgba(255,255,255,0.72)", margin: 0, position: "relative" }}>Last updated: April 18, 2026</p>
      </div>

      {/* Back link */}
      <div style={{ maxWidth: 760, margin: "0 auto", padding: "20px 24px 0" }}>
        <Link to="/login" style={{ fontSize: 13, color: "#7c3aed", textDecoration: "none", fontWeight: 600, display: "inline-flex", alignItems: "center", gap: 4 }}>
          ← Back to Login
        </Link>
      </div>

      {/* Sections */}
      <div style={{ maxWidth: 760, margin: "0 auto", padding: "24px 24px 60px" }}>
        {SECTIONS.map((s) => (
          <div
            key={s.num}
            style={{
              marginBottom: 16,
              background: s.bg,
              border: `1.5px solid ${s.border}`,
              borderLeft: `4px solid ${s.color}`,
              borderRadius: 12,
              padding: "20px 22px",
            }}
          >
            <h2 style={{ fontSize: 16, fontWeight: 700, color: s.color, margin: "0 0 10px", display: "flex", alignItems: "center", gap: 10 }}>
              <span style={{ background: s.color, color: "#fff", borderRadius: "50%", width: 26, height: 26, display: "inline-flex", alignItems: "center", justifyContent: "center", fontSize: 11, fontWeight: 800, flexShrink: 0 }}>
                {s.num}
              </span>
              {s.title}
            </h2>
            <div style={{ fontSize: 14.5, color: "#334155", lineHeight: 1.7 }}>
              {s.content}
            </div>
          </div>
        ))}

        {/* Footer nav */}
        <div style={{ marginTop: 32, textAlign: "center", paddingTop: 24, borderTop: "1.5px solid #e2e8f0" }}>
          <p style={{ fontSize: 13, color: "#64748b", margin: "0 0 12px" }}>Also read our</p>
          <Link to="/privacy" style={{ display: "inline-block", padding: "8px 20px", background: "linear-gradient(135deg, #2563eb, #1d4ed8)", color: "#fff", borderRadius: 20, fontSize: 13, fontWeight: 600, textDecoration: "none", boxShadow: "0 4px 12px rgba(37,99,235,0.3)" }}>
            Privacy Policy →
          </Link>
        </div>
      </div>
    </div>
  );
}
