import { useState } from "react";
import { useNavigate } from "react-router-dom";
import DashboardLayout from "../layout/DashboardLayout";
import api from "../services/api";
import jsPDF from "jspdf";
import html2canvas from "html2canvas";
import { saveAs } from "file-saver";
import { Document, Packer, Paragraph, TextRun, Header, Footer } from "docx";

export default function WorksheetGenerator() {
  const [syllabus, setSyllabus]         = useState("");
  const [subject, setSubject]           = useState("");
  const [grade, setGrade]               = useState("");
  const [topic, setTopic]               = useState("");
  const [difficulty, setDifficulty]     = useState("Medium");
  const [worksheetType, setWorksheetType] = useState("Mixed");
  const [language, setLanguage]         = useState("English");
  const [questionCount, setQuestionCount] = useState(10);

  const [loading, setLoading]   = useState(false);
  const [worksheet, setWorksheet] = useState("");
  const [error, setError]       = useState("");
  const [limitHit, setLimitHit] = useState(false);

  const navigate = useNavigate();

  const handleGenerate = async (e) => {
    e.preventDefault();
    setLoading(true);
    setError("");
    setLimitHit(false);
    setWorksheet("");
    try {
      const res = await api.post("/api/worksheet/generate", {
        syllabus, subject, grade, topic, difficulty, worksheetType, language, questionCount,
      });
      setWorksheet(res.data);
    } catch (err) {
      if (err.response?.status === 402) setLimitHit(true);
      else setError("Failed to generate worksheet. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  const downloadPDF = async () => {
    const element = document.getElementById("worksheet-content");
    if (!element) return;
    const canvas = await html2canvas(element, { scale: 2 });
    const imgData = canvas.toDataURL("image/png");
    const pdf = new jsPDF("p", "mm", "a4");
    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    const headerH = 30, footerH = 20, margin = 10;
    const usableW = pageWidth - margin * 2;
    const usableH = pageHeight - headerH - footerH;
    const imgH = (canvas.height * usableW) / canvas.width;
    let heightLeft = imgH, posY = headerH, page = 1;
    const today = new Date().toLocaleDateString();
    const drawHF = () => {
      pdf.setFontSize(12);
      pdf.text("Worksheet", pageWidth / 2, 15, { align: "center" });
      pdf.setFontSize(10);
      pdf.text(`Subject: ${subject} | Class: ${grade} | Topic: ${topic} | Date: ${today}`, pageWidth / 2, 22, { align: "center" });
      pdf.setFontSize(9);
      pdf.text(`Generated by SmartBoard AI | Page ${page}`, pageWidth / 2, pageHeight - 8, { align: "center" });
    };
    drawHF();
    pdf.addImage(imgData, "PNG", margin, posY, usableW, imgH);
    heightLeft -= usableH;
    while (heightLeft > 0) {
      page++;
      pdf.addPage();
      drawHF();
      posY = headerH - (imgH - heightLeft);
      pdf.addImage(imgData, "PNG", margin, posY, usableW, imgH);
      heightLeft -= usableH;
    }
    pdf.save(`Worksheet_${subject}_Class${grade}.pdf`);
  };

  const downloadWord = async () => {
    const today = new Date().toLocaleDateString();
    const doc = new Document({
      sections: [{
        headers: { default: new Header({ children: [
          new Paragraph({ children: [new TextRun({ text: "Worksheet", bold: true, size: 28 })], alignment: "center" }),
          new Paragraph({ children: [new TextRun({ text: `Subject: ${subject} | Class: ${grade} | Date: ${today}`, size: 22 })], alignment: "center" }),
        ]})},
        footers: { default: new Footer({ children: [new Paragraph({ children: [new TextRun("Generated by SmartBoard AI")], alignment: "center" })] }) },
        children: worksheet.split("\n").map((line) => new Paragraph({ children: [new TextRun({ text: line, size: 22 })] })),
      }],
    });
    const blob = await Packer.toBlob(doc);
    saveAs(blob, `Worksheet_${subject}_Class${grade}.docx`);
  };

  return (
    <DashboardLayout>
      <div className="page-header">
        <h1 className="page-title">Worksheet Generator</h1>
        <p className="page-subtitle">Create printable practice worksheets with answer keys in seconds.</p>
      </div>

      <div className="card" style={{ maxWidth: 760 }}>
        <form onSubmit={handleGenerate}>
          <div className="form-grid">
            <div className="form-field">
              <label className="form-label">Board</label>
              <select className="form-select" value={syllabus} onChange={(e) => setSyllabus(e.target.value)} required>
                <option value="">Select board</option>
                <option>CBSE</option>
                <option>ICSE</option>
                <option>Bihar Board</option>
              </select>
            </div>

            <div className="form-field">
              <label className="form-label">Class</label>
              <select className="form-select" value={grade} onChange={(e) => setGrade(e.target.value)} required>
                <option value="">Select class</option>
                {[...Array(12)].map((_, i) => (
                  <option key={i + 1} value={i + 1}>Class {i + 1}</option>
                ))}
              </select>
            </div>

            <div className="form-field">
              <label className="form-label">Subject</label>
              <input className="form-input" placeholder="e.g. Mathematics" value={subject} onChange={(e) => setSubject(e.target.value)} required />
            </div>

            <div className="form-field">
              <label className="form-label">Worksheet Type</label>
              <select className="form-select" value={worksheetType} onChange={(e) => setWorksheetType(e.target.value)}>
                <option>Mixed</option>
                <option>Fill in the Blanks</option>
                <option>Match the Following</option>
                <option>True / False</option>
                <option>MCQ</option>
                <option>Short Answer</option>
                <option>Long Answer</option>
              </select>
            </div>

            <div className="form-field form-field-full">
              <label className="form-label">Topic</label>
              <input className="form-input" placeholder="e.g. Fractions, Photosynthesis, Mughal Empire" value={topic} onChange={(e) => setTopic(e.target.value)} required />
            </div>

            <div className="form-field">
              <label className="form-label">Difficulty</label>
              <select className="form-select" value={difficulty} onChange={(e) => setDifficulty(e.target.value)}>
                <option>Easy</option>
                <option>Medium</option>
                <option>Hard</option>
              </select>
            </div>

            <div className="form-field">
              <label className="form-label">Language</label>
              <select className="form-select" value={language} onChange={(e) => setLanguage(e.target.value)}>
                <option>English</option>
                <option>Hindi</option>
              </select>
            </div>

            <div className="form-field">
              <label className="form-label">Number of Questions</label>
              <input
                type="number" className="form-input"
                min="5" max="30" value={questionCount}
                onChange={(e) => setQuestionCount(Number(e.target.value))}
              />
            </div>
          </div>

          {limitHit && (
            <div style={{
              marginTop: 16, padding: "16px 20px", borderRadius: 12,
              background: "#fffbeb", border: "1px solid #fcd34d",
              display: "flex", alignItems: "center", justifyContent: "space-between", gap: 12, flexWrap: "wrap",
            }}>
              <div>
                <div style={{ fontWeight: 700, color: "#92400e" }}>Daily limit reached</div>
                <div style={{ fontSize: 13, color: "#b45309" }}>FREE plan allows 2 worksheets/day. Upgrade for unlimited access.</div>
              </div>
              <button className="btn-primary" type="button" onClick={() => navigate("/upgrade")} style={{ whiteSpace: "nowrap" }}>
                Upgrade to PRO
              </button>
            </div>
          )}

          {error && (
            <div className="alert-error" style={{ marginTop: 16 }}>
              <span>⚠️</span> {error}
            </div>
          )}

          <div style={{ marginTop: 20 }}>
            <button type="submit" className="btn-primary" disabled={loading}>
              {loading && <span className="spinner" />}
              {loading ? "Generating…" : "✨ Generate Worksheet"}
            </button>
          </div>
        </form>
      </div>

      {worksheet && (
        <div className="result-box">
          <div className="result-box-header">
            <span className="result-box-title">📋 Worksheet</span>
            <div className="result-box-actions">
              <button className="btn-secondary" onClick={downloadPDF}>⬇ PDF</button>
              <button className="btn-secondary" onClick={downloadWord}>⬇ Word</button>
            </div>
          </div>
          <pre id="worksheet-content" className="result-text">{worksheet}</pre>
        </div>
      )}
    </DashboardLayout>
  );
}
